services:
  - type: web
    name: all-in-one-email-portal
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k gthread -w 1 --threads 4 --timeout 120 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: PASSWORD
        value: "@OLDISGOLD2026@"
    healthCheckPath: /api/health
