services:
  - type: web
    name: all-in-one-email-portal
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: PASSWORD
        value: "@OLDISGOLD2026@"
    healthCheckPath: /api/health
